name: ember_quest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.35.1
  watcher: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/